name: ogdentest
favicon: null
layout_spectrum: 0.7593910829164088
typography_spectrum: 0.7607354165520519
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.11544190696440637
  lightness: 0.4615911382716149
  saturation: 0.2897551632486284
  rhythmicContrast: 0.30408106721006334
purpose: []
